import React, { useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import {
  Eye,
  Download,
  Trash2,
  ChevronLeft,
  ChevronRight,
  X,
  Loader2,
} from "lucide-react";

import {
  deleteCertificate,
  generateBonafide,
  generateTC,
  generateLC,
  generateCharacter,
  downloadCertificate, // Fixed: Added missing import
} from "../../redux/certificate/certificateThunk";

const StatusBadge = ({ status }) => {
  const styles = {
    Generated: "bg-emerald-50 text-emerald-700 border-emerald-200",
    Pending: "bg-amber-50 text-amber-700 border-amber-200",
    Cancelled: "bg-rose-50 text-rose-700 border-rose-200",
    Draft: "bg-slate-50 text-slate-700 border-slate-200",
  };

  return (
    <span
      className={`inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold ${
        styles[status] || styles.Draft
      }`}
    >
      {status || "Draft"}
    </span>
  );
};

const TypeBadge = ({ type }) => {
  const colors = {
    Bonafide: "bg-blue-50 text-blue-700 border-blue-200",
    "Transfer Certificate": "bg-purple-50 text-purple-700 border-purple-200",
    "Leaving Certificate": "bg-orange-50 text-orange-700 border-orange-200",
    "Character Certificate": "bg-emerald-50 text-emerald-700 border-emerald-200",
  };

  return (
    <span
      className={`inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold ${
        colors[type] || "bg-slate-50 text-slate-700 border-slate-200"
      }`}
    >
      {type}
    </span>
  );
};

/* Preview Modal Component */
const PreviewModal = ({ certificate, onClose }) => {
  if (!certificate) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-xs p-4">
      <div className="relative max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-xl bg-white shadow-2xl border border-slate-200">
        <div className="sticky top-0 flex items-center justify-between border-b bg-white px-6 py-4 z-10">
          <h2 className="text-xl font-semibold text-slate-800">
            Certificate Details
          </h2>
          <button
            onClick={onClose}
            className="rounded-lg p-2 text-slate-500 hover:bg-slate-100 transition-colors"
          >
            <X size={20} />
          </button>
        </div>

        <div className="space-y-4 p-6">
          <div className="grid grid-cols-2 gap-4 text-sm">
            <div>
              <p className="text-slate-500 text-xs">Student</p>
              <p className="font-semibold text-slate-800">{certificate.student_name || "—"}</p>
            </div>
            <div>
              <p className="text-slate-500 text-xs">Admission No</p>
              <p className="font-semibold text-slate-800">{certificate.admission_no || "—"}</p>
            </div>
            <div>
              <p className="text-slate-500 text-xs">Class / Section</p>
              <p className="font-semibold text-slate-800">
                {certificate.class_name || "-"} {certificate.section_name || ""}
              </p>
            </div>
            <div>
              <p className="text-slate-500 text-xs">Certificate Type</p>
              <p className="font-semibold text-slate-800">{certificate.certificate_type || "—"}</p>
            </div>
            <div>
              <p className="text-slate-500 text-xs">Certificate No</p>
              <p className="font-semibold text-slate-800">{certificate.certificate_no || "—"}</p>
            </div>
            <div>
              <p className="text-slate-500 text-xs">Issue Date</p>
              <p className="font-semibold text-slate-800">{certificate.issue_date || "—"}</p>
            </div>
            <div>
              <p className="text-slate-500 text-xs">Status</p>
              <div className="mt-1">
                <StatusBadge status={certificate.status} />
              </div>
            </div>
            <div>
              <p className="text-slate-500 text-xs">Generated By</p>
              <p className="font-semibold text-slate-800">{certificate.generated_by || "—"}</p>
            </div>
          </div>

          <div>
            <p className="mb-1 text-slate-500 text-xs">Reason</p>
            <p className="rounded-lg bg-slate-50 p-3 text-sm border text-slate-700">
              {certificate.reason || "—"}
            </p>
          </div>

          <div>
            <p className="mb-1 text-slate-500 text-xs">Remarks</p>
            <p className="rounded-lg bg-slate-50 p-3 text-sm border text-slate-700">
              {certificate.remarks || "—"}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

const CertificateTable = ({
  data = [],
  loading,
  page,
  totalPages,
  filters,
  setFilters,
}) => {
  const dispatch = useDispatch();
  const [previewItem, setPreviewItem] = useState(null);
  const [downloadingId, setDownloadingId] = useState(null);

  const handleDelete = (id) => {
    if (!window.confirm("Are you sure you want to delete this certificate?")) return;
    dispatch(deleteCertificate(id));
  };

  const handleDownload = async (item) => {
    if (!item.student_id) {
      alert("Missing student reference on this certificate.");
      return;
    }

    setDownloadingId(item.certificate_id);

    const payload = {
      reason: item.reason,
      remarks: item.remarks,
      issue_date: item.issue_date,
      certificate_no: item.certificate_no,
    };

    try {
      if (item.pdf_path) {
        await dispatch(downloadCertificate(item.certificate_id, item.certificate_no));
        return;
      }

      switch (item.certificate_type) {
        case "Bonafide":
          await dispatch(generateBonafide(item.student_id));
          break;
        case "Transfer Certificate":
          await dispatch(generateTC(item.student_id, payload));
          break;
        case "Leaving Certificate":
          await dispatch(generateLC(item.student_id, payload));
          break;
        case "Character Certificate":
          await dispatch(generateCharacter(item.student_id, payload));
          break;
        default:
          alert("Unknown certificate type — cannot generate PDF.");
      }
    } finally {
      setDownloadingId(null);
    }
  };

  if (loading) {
    return (
      <div className="flex h-64 items-center justify-center rounded-xl border bg-white p-10 shadow-xs">
        <div className="flex items-center gap-2 text-slate-500">
          <Loader2 className="animate-spin" size={20} />
          <span>Loading certificates...</span>
        </div>
      </div>
    );
  }

  return (
    <div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-xs">
      <div className="overflow-x-auto">
        <table className="min-w-full divide-y divide-slate-200 text-sm">
          <thead className="bg-slate-50 text-slate-600 font-medium">
            <tr>
              <th className="px-5 py-3.5 text-left">Student</th>
              <th className="px-5 py-3.5 text-left">Admission No</th>
              <th className="px-5 py-3.5 text-left">Certificate</th>
              <th className="px-5 py-3.5 text-left">Issue Date</th>
              <th className="px-5 py-3.5 text-left">Status</th>
              <th className="px-5 py-3.5 text-center">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100 bg-white">
            {data.length === 0 ? (
              <tr>
                <td colSpan={6} className="py-12 text-center text-slate-500">
                  No Certificates Found
                </td>
              </tr>
            ) : (
              data.map((item) => (
                <tr key={item.certificate_id} className="hover:bg-slate-50/80 transition-colors">
                  <td className="px-5 py-4 font-medium text-slate-900">
                    {item.student_name}
                  </td>
                  <td className="px-5 py-4 text-slate-600">{item.admission_no}</td>
                  <td className="px-5 py-4">
                    <TypeBadge type={item.certificate_type} />
                  </td>
                  <td className="px-5 py-4 text-slate-600">{item.issue_date}</td>
                  <td className="px-5 py-4">
                    <StatusBadge status={item.status} />
                  </td>
                  <td className="px-5 py-4">
                    <div className="flex justify-center gap-1">
                      <button
                        onClick={() => setPreviewItem(item)}
                        className="rounded-lg p-2 text-slate-600 hover:bg-slate-100 hover:text-blue-600 transition-colors"
                        title="Preview"
                      >
                        <Eye size={18} />
                      </button>
                      <button
                        onClick={() => handleDownload(item)}
                        disabled={downloadingId === item.certificate_id}
                        className="rounded-lg p-2 text-slate-600 hover:bg-slate-100 hover:text-emerald-600 disabled:opacity-40 transition-colors"
                        title="Download PDF"
                      >
                        {downloadingId === item.certificate_id ? (
                          <Loader2 size={18} className="animate-spin text-emerald-600" />
                        ) : (
                          <Download size={18} />
                        )}
                      </button>
                      <button
                        onClick={() => handleDelete(item.certificate_id)}
                        className="rounded-lg p-2 text-slate-600 hover:bg-slate-100 hover:text-rose-600 transition-colors"
                        title="Delete"
                      >
                        <Trash2 size={18} />
                      </button>
                    </div>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      <div className="flex items-center justify-between border-t border-slate-200 px-5 py-3.5 bg-slate-50/50">
        <button
          disabled={page <= 1}
          onClick={() => setFilters({ ...filters, page: page - 1 })}
          className="flex items-center gap-1.5 rounded-lg border bg-white px-3 py-1.5 text-xs font-medium text-slate-700 shadow-2xs hover:bg-slate-50 disabled:opacity-40 transition-colors"
        >
          <ChevronLeft size={16} /> Previous
        </button>
        <span className="text-xs font-medium text-slate-600">
          Page {page} of {totalPages || 1}
        </span>
        <button
          disabled={page >= totalPages}
          onClick={() => setFilters({ ...filters, page: page + 1 })}
          className="flex items-center gap-1.5 rounded-lg border bg-white px-3 py-1.5 text-xs font-medium text-slate-700 shadow-2xs hover:bg-slate-50 disabled:opacity-40 transition-colors"
        >
          Next <ChevronRight size={16} />
        </button>
      </div>

      <PreviewModal
        certificate={previewItem}
        onClose={() => setPreviewItem(null)}
      />
    </div>
  );
};

export default CertificateTable;